# Generated by Django 4.2.9 on 2024-02-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_nm', models.CharField(max_length=20)),
                ('medical_use', models.CharField(max_length=200)),
                ('title_image', models.CharField(max_length=200)),
                ('drug_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('ctgry_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctgry_nm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnintendedDrugUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('usage_title', models.CharField(max_length=225)),
                ('usage_ctnt', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='DrugImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeguardian.drug')),
            ],
        ),
        migrations.CreateModel(
            name='DrugFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_feature', models.CharField(max_length=200)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeguardian.drug')),
            ],
        ),
        migrations.CreateModel(
            name='DrugAdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_nm', models.CharField(max_length=225)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeguardian.drug')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='ctgry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeguardian.drugcategory'),
        ),
    ]
