# Generated by Django 4.2.9 on 2024-02-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeguardian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugadr',
            old_name='drug_id',
            new_name='drug',
        ),
        migrations.RenameField(
            model_name='drugfeature',
            old_name='drug_id',
            new_name='drug',
        ),
        migrations.RenameField(
            model_name='drugimage',
            old_name='drug_id',
            new_name='drug',
        ),
    ]
