# Generated by Django 4.2.9 on 2024-02-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeguardian', '0002_rename_drug_id_drugadr_drug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='ctgry_id',
            new_name='ctgry',
        ),
    ]
