# Generated by Django 4.2.9 on 2024-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeguardian', '0004_alter_drug_title_image_alter_drugimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unintendeddrugusage',
            name='usage_image',
            field=models.URLField(default='', max_length=225),
        ),
    ]
